export const configuration = () => ({
  NODE_ENV: process.env.NODE_ENV,
  PORT: process.env.PORT ?? 8080,
  TOKEN: process.env.TOKEN,
  DB_PREFIX: process.env.DB_PREFIX,
  GCLOUD_PROJECT: process.env.GCLOUD_PROJECT,
  SESSION_SECRET: process.env.SESSION_SECRET,
  RTM_URL: process.env.RTM_URL,
  RTM_TOKEN: process.env.RTM_TOKEN,
  JWT_SECRET: process.env.JWT_SECRET,
  MAP_WIDTH: process.env.MAP_WIDTH,
  MAP_HEIGHT: process.env.MAP_HEIGHT,
  CLIENT_EMAIL: process.env.CLIENT_EMAIL,
  PRIVATE_KEY: process.env.PRIVATE_KEY,
  PROJECT_ID: process.env.PROJECT_ID,
});
